plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.6'
    id 'com.enonic.xp.app'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation xplibs.api.core
    implementation xplibs.api.portal
    implementation "com.enonic.xp:core-elasticsearch:${xpVersion}"
    include "com.enonic.lib:lib-thymeleaf:3.0.0-SNAPSHOT"
    include xplibs.content
    include xplibs.portal
    include xplibs.node
    include xplibs.repo
    include xplibs.task
    include xplibs.event
    include xplibs.websocket
}

repositories {
    mavenCentral()
    xp.enonicRepo( "dev" )
}
