plugins {
    id 'maven-publish'
    id 'com.enonic.defaults' version '2.1.7'
    id 'com.enonic.xp.app'
}

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

dependencies {
    testImplementation libs.junit
    implementation xplibs.api.core
    implementation xplibs.api.portal
    implementation "com.enonic.xp:core-elasticsearch:${xpVersion}"
    compileOnly "org.elasticsearch:elasticsearch:9.5.3"
    implementation libs.jackson.databind
    implementation libs.jackson.datatype.jsr310
    include libs.lib.thymeleaf
    include libs.lib.asset
    include xplibs.content
    include xplibs.portal
    include xplibs.node
    include xplibs.repo
    include xplibs.task
    include xplibs.event
    include xplibs.websocket
}

repositories {
    mavenCentral()
    xp.enonicRepo( "dev" )
}
