[versions]
asset = "2.0.1"
jackson = "2.22.2"
junit = "4.13.2"
thymeleaf = "3.0.0"

[libraries]
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310", version.ref = "jackson" }
junit = { module = "junit:junit", version.ref = "junit" }
lib-asset = { module = "com.enonic.lib:lib-asset", version.ref = "asset" }
lib-thymeleaf = { module = "com.enonic.lib:lib-thymeleaf", version.ref = "thymeleaf" }
